spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/2023ProjectsDB?currentSchema=Jira'
    username: 'postgres'
    password: 'root'

    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: 'Jira'
      show-sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true

server:
  port: 8080