package com.example.Jira.entity.states;

public enum Roles {
    ADMIN,
    PROJECT_MANAGER, // PROJECT_MANAGER
    EXPERT, // EXPERT
    FRONTEND_DEVELOPER, // FRONTEND_DEVELOPER
    BACKEND_DEVELOPER, //  BACKEND_DEVELOPER
    DEVOPS // DEVOPS
}
